export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCEESS = 'FETCH_DATA_SUCCEESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
//add
export const ADD_DATA_SUCCEESS = 'ADD_DATA_SUCCEESS';
export const ADD_DATA_FAIL = 'ADD_DATA_FAIL';
//DELETE
export const DELETE_DATA_SUCCEESS = 'DELETE_DATA_SUCCEESS';
export const DELETE_DATA_FAIL = 'DELETE_DATA_FAIL';
//edit
export const EDIT_DATA_SUCCEESS = 'EDIT_DATA_SUCCEESS';
export const EDIT_DATA_FAIL = 'EDIT_DATA_FAIL';
